//
// Created by volkert on 1/5/24.
// This file is normally autogenerated by ./configure.h of pciutils
//

#ifndef DOS_VIRTIO_SND_CONFIG_H
#define DOS_VIRTIO_SND_CONFIG_H

#define PCI_PATH_IDS_DIR "./"
#define PCI_IDS "pci.ids"

#endif //DOS_VIRTIO_SND_CONFIG_H
